### ISSUE TITLE
error while loading shared libraries: libhts.so.2

### ISSUE THREAD

**Issue by kpatankar** [genome/pindel#101]
Hi,

I installed pindel. When I run the .`/pindel` command it gives me following error.

`./pindel: error while loading shared libraries: libhts.so.2: cannot open shared object file: No such file or directory`

To resolve this I performed following steps:
find ~ -name libhts.so.2

It gave me the following path
/home/kalyani/bin/htslib-1.9/libhts.so.2

export LD_LIBRARY_PATH=/home/kalyani/htslib-1.6/libhts.so.2

It still gives me the error regarding the htslib.so.2 not found.

Are there some steps which I am missing?
 Appreciate your response.

Thanks!!!

**Comment by kpatankar** [comment]
Hi,

The issue was resolved by command:

`export LD_LIBRARY_PATH=/home/kalyani/htslib-1.6/`

`./pindel` running successfully.

**Comment by luistatlav** [comment]
I had a similar problem with the program **gencore**:

`./gencore`

> ./gencore: error while loading shared libraries: libhts.so.2to3part5: cannot open shared object file: No such file or directory

Thanks for you command. It resolved the problem.

**Comment by Yuxinagli** [comment]
hi, luistatlav. I have the same problem with yours. How did you solve it since it's libhts.so.2to3part5 missing not the libhts.so? Thanks!!

**Comment by luistatlav** [comment]
> hi, luistatlav. I have the same problem with yours. How did you solve it since it's libhts.so.2to3part5 missing not the libhts.so? Thanks!!

Hi @Yuxinagli, I had the problem on subsystem of linux for Windows. I did the same that @kpatankar:

> The issue was resolved by command: 
> `export LD_LIBRARY_PATH=/home/NameOfUser/htslib-1.6/`

and `./gencore` running successfully.

**Comment by Yuxinagli** [comment]
> > hi, luistatlav. I have the same problem with yours. How did you solve it since it's libhts.so.2to3part5 missing not the libhts.so? Thanks!!
> 
> Hi @Yuxinagli, I had the problem on subsystem of linux for Windows. I did the same that @kpatankar:
> 
> > The issue was resolved by command:
> > `export LD_LIBRARY_PATH=/home/NameOfUser/htslib-1.6/`
> 
> and `./gencore` running successfully.

Thanks, @luistatlav ! It works with this modification in the ~/.bashrc  .
