### ISSUE TITLE
build error; ‘bam_header_t {aka struct bam_hdr_t}’ has no member named ‘dict’

### ISSUE THREAD

**Issue by fizwit** [genome/pindel#90]
gcc 5.4.0
using CPATH to define HTSlib and SAMtools  versions 1.8.0

make -C src pindel
make[1]: Entering directory `/home/jfdey/sources/pindel-0.2.5/src'
g++  -Wall -g -c -O3 -fopenmp -I/app/easybuild/software/HTSlib/1.8-foss-2016b/include/ search_MEI_util.cpp -o search_MEI_util.o
search_MEI_util.cpp: In function ‘std::map<std::__cxx11::basic_string<char>, std::__cxx11::basic_string<char> > get_sample_dictionary(bam_header_t*)’:
search_MEI_util.cpp:346:17: error: ‘bam_header_t {aka struct bam_hdr_t}’ has no member named ‘dict’
     if (header->dict == 0) header->dict = sam_header_parse2(header->text);
                 ^
search_MEI_util.cpp:346:36: error: ‘bam_header_t {aka struct bam_hdr_t}’ has no member named ‘dict’
     if (header->dict == 0) header->dict = sam_header_parse2(header->text);
                                    ^
search_MEI_util.cpp:357:39: error: ‘bam_header_t {aka struct bam_hdr_t}’ has no member named ‘dict’
     tmp_ids = sam_header2list(header->dict, rg_tag, id_tag, &num_ids);
                                       ^
search_MEI_util.cpp:359:41: error: ‘bam_header_t {aka struct bam_hdr_t}’ has no member named ‘dict’
     tmp_names = sam_header2list(header->dict, rg_tag, sm_tag, &num_names);
                                         ^
make[1]: *** [search_MEI_util.o] Error 1
make[1]: Leaving directory `/home/jfdey/sources/pindel-0.2.5/src'
make: *** [pindel] Error 2

Creating pindel2vcf utility...
pindel2vcf created.

Creating sam2pindel utility...
sam2pindel created.
mv: cannot stat ‘src/pindel’: No such file or directory

Pindel successfully compiled. The pindel executable can be found in this directory.

**Comment by jmarshall** [comment]
Pindel v0.2.5 is from 2013, which was before PR #12 — which made Pindel require only HTSlib, not samtools. And these errors concern `bam_header_t`, which was part of the legacy samtools API.

You will not have these errors if you use the most recent release (v0.2.5b8) or current git.

**Comment by fizwit** [comment]
v0.2.5b8 built successfully
